from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

def create_presentation():
    prs = Presentation()

    # Slide 1: Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Maou-Sama-TD: Development Journey"
    subtitle.text = "Game Mechanics, Custom Tools, AI Integration & Roadmap\nGenerated by Antigravity AI"

    # Slide 2: Tech Stack & Architecture (Layout 3 = Two Content)
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Technology Stack"
    content = slide.placeholders[1]
    tf = content.text_frame
    p = tf.add_paragraph()
    p.text = "Game Engine: Unity (C#)"
    p = tf.add_paragraph()
    p.text = "Automation Framework (Salavan): Python & PySide6 UI"
    p = tf.add_paragraph()
    p.text = "Test Scripting: Lua (via Salavan GameHooks)"
    p = tf.add_paragraph()
    p.text = "Asset Management: Unity Addressables for modular loading"
    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., Unity Editor or Code Snippet)"

    # Slide 3: Game Mechanics Inspiration
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Game Mechanics Inspiration"
    content = slide.placeholders[1]
    tf = content.text_frame
    p = tf.add_paragraph()
    p.text = "Tower Defense Core: Strategic placement, waves, and Sovereign defense."
    p = tf.add_paragraph()
    p.text = "Gacha & Ascension: Character pulls, dice-rolled ascension stats, and varied rarities."
    p = tf.add_paragraph()
    p.text = "Dynamic Maps & Classes: Procedural elements, environmental hazards, and complex class scalings."
    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., Gameplay / Ascension Dice Roll)"

    # Slide 4: Mythic Frame & AI Integration
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Mythic Frame & AI Integration"
    content = slide.placeholders[1]
    tf = content.text_frame
    p = tf.add_paragraph()
    p.text = "Mythic Frame: A custom wrapper built for Gemini 3.1 via Google AI Studio."
    p = tf.add_paragraph()
    p.text = "AI Art Generation: Mythic Frame handles dynamic image generation, directly generating and syncing art assets into Unity."
    p = tf.add_paragraph()
    p.text = "Narrative Studio: Writer AI automates the generation of in-game lore, dialogues, and storyline text."
    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., AI Art Generator UI or Mythic Frame Wrapper)"

    # Slide 5: Comprehensive Editor Tools
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Custom Editor & SO Tools"
    content = slide.placeholders[1]
    tf = content.text_frame
    p = tf.add_paragraph()
    p.text = "A massive suite of editor extensions was created to manage the game data:"
    tools = [
        "Stat Balancing Studio",
        "Narrative Studio & Dialogue Tester",
        "Unit Browser & Enemy Browser",
        "Campaign Map Browser",
        "Sovereign Rite Browser",
        "Bestiary (Beastiry) Editor",
        "Class Scaling & Job Tools",
        "Tutorial Tester",
        "Swift Click Tools"
    ]
    for tool in tools:
        p2 = tf.add_paragraph()
        p2.text = tool
        p2.level = 1
    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., The Unity Tools Menu Dropdown)"

    # Slide 6: Gameplay Interactions, Events & Settings
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Interactions, Events & Settings"
    content = slide.placeholders[1]
    tf = content.text_frame
    p = tf.add_paragraph()
    p.text = "Core Interactions: Drag-and-drop unit deployment, Ultimate casting, dynamic game speed controls, and interactive dialogues."
    p = tf.add_paragraph()
    p.text = "Game Events: Rich event system handling Wave Start, Unit Spawned, Stage Cleared, and Narrative Triggers."
    p = tf.add_paragraph()
    p.text = "Settings & Localization: Comprehensive volume controls, display settings, and multi-language support integration."
    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., Settings Menu or In-Game Interaction HUD)"

    # Slide 7: Salavan & Workflow Automation
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Salavan & Test Automation"
    content = slide.placeholders[1]
    tf = content.text_frame
    p = tf.add_paragraph()
    p.text = "Salavan Framework: Desktop app executing headless/UI scenarios."
    p = tf.add_paragraph()
    p.text = "GameState Exporter: Unity script extracting UI elements, HP, and events to JSON in real-time."
    p = tf.add_paragraph()
    p.text = "Lua Scenarios: End-to-end testing of features like 'Fresh Start' and battle simulation."
    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., Salavan Desktop UI)"

    # Slide 8: Automation Challenges
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Testing Challenges: Intro Dialogue Bug"
    content = slide.placeholders[1]
    tf = content.text_frame
    p = tf.add_paragraph()
    p.text = "Issue: 'Intro Dialogue' step was erroneously marked as PASS before completion."
    p = tf.add_paragraph()
    p.text = "Cause: The dialogue state briefly flipped to 'false' during panel transitions, causing the loop to break early."
    p = tf.add_paragraph()
    p.text = "Resolution: Implemented robust verification via wildcard matching for '*Skip*' buttons and extended loop delays."
    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., The screenshot showing the stuck dialogue)"

    # Slide 9: Future Plans & Roadmap
    slide = prs.slides.add_slide(prs.slide_layouts[3])
    title = slide.shapes.title
    title.text = "Future Plans & Roadmap"
    content = slide.placeholders[1]
    tf = content.text_frame
    
    plans = [
        "Lore & Narrative: Adding deep character 'Chambers' and dating events.",
        "New Game Mode: A dedicated mini-game mode where you play exclusively as Maou.",
        "Combat Upgrades: More abilities, VFX, and devastating Ultimate animations.",
        "Visual Enhancements: Redrawing existing characters, adding animated splash screens, and implementing improved 3D map textures/lighting.",
        "Expanded Roster: Currently, the main important allies are Ignis, Lilith, and Tina. More story characters are in the works!"
    ]
    for plan in plans:
        p2 = tf.add_paragraph()
        p2.text = plan
        p2.level = 0

    slide.placeholders[2].text = "[ INSERT SCREENSHOT HERE ]\n(e.g., Concept Art, New Map Mockup, or Character Splashes)"

    prs.save('Maou_Sama_TD_Presentation_v2.pptx')
    print("Presentation successfully updated with Interactions, Settings, and Future Plans slides!")

if __name__ == "__main__":
    create_presentation()
